# Manual ESPHome entry point for the experimental JC8012P4A1 V3 branch.
substitutions:
  name: "espctl-v3-test"
  friendly_name: "EspControl 10inch V3 Test"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  api_encryption:
    url: https://github.com/jtenniswood/espcontrol/
    ref: test-jc8012p4a1-v3
    file: common/addon/api_encryption_dynamic.yaml
    refresh: 1s
  setup:
    url: https://github.com/jtenniswood/espcontrol/
    ref: test-jc8012p4a1-v3
    file: devices/guition-esp32-p4-jc8012p4a1-v3-test/test-package.yaml
    refresh: 1s
