#!/usr/bin/env python3
"""Generate compact media emoji properties from Unicode 17.0 emoji-data.txt.

Download https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-data.txt,
then pass its local path. Normal firmware builds do not need this download.
"""
import argparse
from pathlib import Path


def generate(source: str) -> str:
    if "Version: 17.0" not in source:
        raise ValueError("Expected Unicode Emoji Version: 17.0 data")
    output = [
        "// Generated by scripts/generate_media_emoji_ranges.py; do not edit.",
        "// Unicode 17.0: https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-data.txt",
        "// Copyright (c) 2025 Unicode, Inc.",
        "// Unicode-3.0 license: see UNICODE-LICENSE.txt alongside this file.",
        "#pragma once", "", "#include <cstdint>", "",
        "namespace espcontrol::media::text_detail {",
        "struct Range { uint32_t first; uint32_t last; };", "",
    ]
    for prop, name in (("Emoji", "EMOJI"),):
        ranges = []
        for line in source.splitlines():
            fields = line.split("#", 1)[0].strip().split(";")
            if len(fields) != 2 or fields[1].strip() != prop:
                continue
            bounds = fields[0].strip().split("..")
            first, last = int(bounds[0], 16), int(bounds[-1], 16)
            if ranges and first == ranges[-1][1] + 1:
                ranges[-1] = (ranges[-1][0], last)
            else:
                ranges.append((first, last))
        output.append(f"inline constexpr Range {name}[] = {{")
        output.extend(f"  {{0x{first:X}, 0x{last:X}}}," for first, last in ranges)
        output.extend(("};", ""))
    output.append("}  // namespace espcontrol::media::text_detail")
    return "\n".join(output) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("emoji_data", type=Path)
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "components/espcontrol/media_emoji_ranges.h"
    target.write_text(generate(args.emoji_data.read_text(encoding="utf-8")), encoding="utf-8")
